### ISSUE TITLE
Session Set UID value is 0 will not general _csrf value

### ISSUE THREAD

**Issue by genedna** [macaron-contrib/csrf#3]
My middleware config

```
	m.Use(csrf.Csrfer(csrf.Options{
		Secret:     "dockercnxcsrftoken",
		Header:     "X-CSRFToken",
		SessionKey: "uid",
		SetCookie:  true,
		SetHeader:  true,
	}))
```

and behind the session config.

When I set `session.Set("uid", 0)` in the handler function, will not general `_csrf` function in the Header.

**Comment by Unknwon** [comment]
Fixed by https://github.com/macaron-contrib/csrf/commit/0de1adf19f90897df65f74bef7a0fe270cc54613
